apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: xihe-test-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sync-repo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-kafka: "0600"
        vault.hashicorp.com/agent-inject-perms-redis.crt: "0600"
        vault.hashicorp.com/agent-inject-perms-mysql.crt: "0600"
        vault.hashicorp.com/agent-inject-perms-mq.crt: "0600"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-application.yml: xihe/data/conf
        vault.hashicorp.com/agent-inject-template-application.yml: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.syncrepo }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-kafka: xihe/data/conf
        vault.hashicorp.com/agent-inject-template-kafka: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.kafka }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-redis.crt: "xihe/data/conf"
        vault.hashicorp.com/agent-inject-template-redis.crt: |
          {{- with secret "xihe/data/conf" -}}
          {{ .Data.data.RedisCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mysql.crt: "xihe/data/conf"
        vault.hashicorp.com/agent-inject-template-mysql.crt: |
          {{- with secret "xihe/data/conf" -}}
          {{ .Data.data.MysqlCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mq.crt: xihe/data/conf/
        vault.hashicorp.com/agent-inject-template-mq.crt: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.MqCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        component: sync-repo
    spec:
      serviceAccount: xihe-test
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: sync-repo
        args:
        - --port=8000
        - --config-file=/vault/secrets/application.yml
        - --enable_debug=false
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
