---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneid-server
  namespace: om-webserver
spec:
  replicas: 0
  selector:
    matchLabels:
      app: oneid-server
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'freesky-hk-opengauss-omwebserver'
        vault.hashicorp.com/agent-inject-secret-application.yml: 'internal/data/infra-common/opengauss-omwebserver'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-application.yml: |  
          {{- with secret "internal/data/infra-common/opengauss-omwebserver" -}}  
          {{ .Data.data.OneidServer }}
          {{- end }}
      labels:
        app: oneid-server
    spec:
      serviceAccountName: opengauss-omwebserver
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: oneid-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/oneid-server:8001dddc3e93c34ebd3496a0d32d2c328ff4c6a2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: APPLICATION_PATH
          value: "/vault/secrets/application.yml"
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi