apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: ubuntu
  kubernetes.ops.owner: guodaxing
  kubernetes.ops.region: hk
kind: Kustomization
namespace: openguardfuzz-webserver
resources:
- bot-deployment.yaml
- autoscaler.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openguardfuzz-bot
  newTag: test-8ecde7
