---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: majuncommitlog
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: csi-disk