---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: mindspore-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'freesky-hk-mindspore-website'
        vault.hashicorp.com/agent-inject-perms-application.yaml: "0600"
        vault.hashicorp.com/agent-run-as-user: "1001"
        vault.hashicorp.com/agent-inject-secret-application.yaml: 'internal/data/mindspore/website'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-application.yaml: |  
          {{- with secret "internal/data/mindspore/website" -}}  
          {{ .Data.data.api }}
          {{- end }}
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      serviceAccountName: mindspore-website
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        - name: APPLICATION_PATH
          value: "/vault/secrets/application.yaml"
        image: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/icsl/mindspore-website-api:master-3c8578
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: server
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        volumeMounts:
        - mountPath: /mnt/share/file
          name: website-data-volume
        - mountPath: /opt/sql
          name: sql-config-volume
      volumes:
      - name: website-data-volume
        persistentVolumeClaim:
          claimName: website-data
      - name: sql-config-volume
        persistentVolumeClaim:
          claimName: mindspore-api-sql-file-03