resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
- configmap.yaml
- autoscaler.yaml
namespace: openeuler-website
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 845831435@qq.com
  kubernetes.ops.os.base: openEuler
  kubernetes.ops.owner: wangxing
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler-website-test
  newTag: v1.0.20231027160854
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-portal
  newTag: 5bc8e56f3c40bdd1986183d006c3ea00206f02cf
