apiVersion: apps/v1
kind: Deployment
metadata:
  name: big-model-finetune-deployment
  namespace: xihe-test-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: big-model-finetune
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/secret-volume-path: "/bigmodel-finetune/conf/"
        vault.hashicorp.com/agent-inject-perms-finetune_basic.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-asset.yml: "0600"
        vault.hashicorp.com/agent-inject-perms-mysql.crt: "0600"
        vault.hashicorp.com/agent-run-as-user: "5000"
        vault.hashicorp.com/agent-inject-secret-finetune_basic.yml: xihe/data/conf
        vault.hashicorp.com/agent-inject-template-finetune_basic.yml: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.finetuneBasic }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-asset.yml: xihe/data/conf
        vault.hashicorp.com/agent-inject-template-asset.yml: |
          {{- with secret "xihe/data/conf/" -}}
          {{ .Data.data.finetuneAsset }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mysql.crt: "xihe/data/conf"
        vault.hashicorp.com/agent-inject-template-mysql.crt: |
          {{- with secret "xihe/data/conf" -}}
          {{ .Data.data.MysqlCA }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-test
      labels:
        app: big-model-finetune
    spec:
      serviceAccount: xihe-test
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
      - key: "icsl"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/big-model-finetune:c409315983b32f9ea44dae3c51e2a54123a5673e
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: big-model-finetune
        env:
        - name: CPU_COUNT
          value: "4"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 3000Mi
          requests:
            cpu: 1000m
            memory: 1500Mi
