resources:
- ingress.yaml
- service.yaml
- deployment.yaml
- autoscaler.yaml
- secret.yaml
- cronjob.yaml
namespace: opengauss-website-revision
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: liuqi
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/meeting-server-test
  newTag: 9ae5b37bc4ffd17f3a61958d00abcf2d44dd0052
