apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: openlookeng-website-ingress-main
  namespace: openlookeng-website
  labels: 
    app: openlookeng-website
spec:
  tls:
    - hosts:
        - openlookeng.test.osinfra.cn
      secretName: openlookeng-website-tls
  rules:
    - host: openlookeng.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: openlookeng-website-frontend-service
              servicePort: 80
            path: /
