resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
- autoscaler.yaml
commonLabels:
  app: openlookeng-website
namespace: openlookeng-website
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: 1456889284@qq.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: panxiangqu
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/test_openlookeng_website
  newTag: fb8457ce4f21186b47cd64f36b5e2557449c39b2
