resources:
- data-cache.yaml
- event-retriever-deployment.yaml
- event-retriever-ingress.yaml
- event-retriever-secret.yaml
- event-retriever-service.yaml
- rabbitmq.yaml
- rule-handler.yaml
- strategy-executor.yaml
- sunmao-namespace.yaml
namespace: sunmao
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/sunmao/data-cache
  newTag: v1.0.20231024195255
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/sunmao/event-retriever
  newTag: v1.0.20231024195130
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/sunmao/rabbitmq
  newTag: cc65de431e81e0542b32516af554a03c4ce36f7c
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/sunmao/rule-handler
  newTag: v1.0.20231024195455
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/sunmao/strategy-executor
  newTag: v1.0.20231024195517
