---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/disk-volume-type: ssd
  name: openeuler-sync-bot-volume
  namespace: sync-bot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-disk-sas
  volumeMode: Filesystem
