---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: sync-bot-osinfra-cn-tls
  namespace: sync-bot
spec:
  name: sync-bot-osinfra-cn-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.key:
      path: secrets/data/infra-test/domain-tls
      key: tls.key