resources:
- deployment.yaml
- namespace.yaml
- service.yaml
commonAnnotations:
  kubernetes.ops.cluster: freesky-icsl-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: hk
namespace: openlookeng-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/icsl/openlookeng-website
  newTag: 9a4ce9cf192dd718a7b53608bb654875d271d079
