apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-search-deployment
  namespace: mindspore-doc-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-search
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'freesky-hk-mindspore-search'
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-run-as-user: "1001"
        vault.hashicorp.com/agent-inject-secret-application.yml: 'internal/data/mindspore/search-icsl'
        vault.hashicorp.com/agent-inject-template-application.yml: |  
          {{- with secret "internal/data/mindspore/search-icsl" -}}  
          {{ .Data.data.application }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
      labels:
        app: doc-search
    spec:
      serviceAccount: mindspore-search
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        - name: X_ARMOR_BACKEND_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_tenant_id
        - name: X_ARMOR_BACKEND_APP_ID
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_app_id
        - name: X_ARMOR_BACKEND_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_backend_app_token
        - name: X_ARMOR_SECURITY_ENABLE
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_security_enable
        - name: X_ARMOR_SECURITY_ROOT_PASSWORD_0
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_security_root_password
        - name: X_ARMOR_SECURITY_WORK_PASSWORD_0
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_secutiry_work_password
        - name: X_ARMOR_BACKEND_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_backend_url
        - name: APPLICATION_PATH
          value: "/vault/secrets/application.yml"
        - name: MINDSPORE_OFFICIAL
          value: "https://mindspore.myopeninfra.com"
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/mindspore-search:7332da50ec635bfa39629a7b49dd291295af920d
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: doc-search
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 1000m
            memory: 2000Mi
        volumeMounts:
        - mountPath: /opt/sql
          name: sql-config-volume
      volumes:
      - name: sql-config-volume
        persistentVolumeClaim:
          claimName: mindspore-doc-search-ssl
