apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: freesky-icsl-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: chenyang
  kubernetes.ops.region: shanghai
kind: Kustomization
namespace: mindspore-doc-search
resources:
- namespace.yaml
- doc-search-ingress.yaml
- doc-search-service.yaml
- doc-search-secret.yaml
- doc-search-deployment.yaml
- pvc.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/mindspore-search
  newName: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/icsl/mindspore-search
  newTag: 4b3fb20d2198fb34bbfc0fd796e35931742bfd4b
