apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    csi.storage.k8s.io/fstype: obsfs
    csi.storage.k8s.io/node-publish-secret-name: cce-mount-obs-aksk
    csi.storage.k8s.io/node-publish-secret-namespace: mindspore-website
    everest.io/enterprise-project-id: "0"
    everest.io/obs-volume-type: STANDARD
    pv.kubernetes.io/bind-completed: "yes"
    volume.beta.kubernetes.io/storage-provisioner: everest-csi-provisioner
  finalizers:
  - kubernetes.io/pvc-protection
  name: mindspore-doc-search-ssl
  namespace: mindspore-doc-search
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-obs
  volumeMode: Filesystem
  volumeName: pv-obs-mindspore-search-icsl