apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/xihe-website
  newTag: stable-e48656
