---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengauss-website
  namespace: opengauss-website
  labels:
    app: opengauss-website
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.websiteinfod: semver:~1.0
spec:
  selector:
    matchLabels:
      app: opengauss-website
  template:
    metadata:
      labels:
        app: opengauss-website
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      nodeSelector:
        autoscaler: "true"
      containers:
      - name: websiteinfod
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/test_opengauss_website:v1.0.20220621112656
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
