apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: opengauss-website-ingress
  namespace: opengauss-website
  labels: 
    app: opengauss-website
spec:
  tls:
    - hosts:
        - opengauss.test.osinfra.cn
      secretName: opengauss-website-tls
  rules:
    - host: opengauss.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: opengauss-website-service
              servicePort: 8080
            path: /
