apiVersion: v1
kind: Service
metadata:
  name: opengauss-website-service
  namespace: opengauss-website
spec:
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: opengauss-website
  type: ClusterIP
