apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wangshuiquan
  kubernetes.ops.region: hk
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/certificate-center-test
  newTag: master-cb83aa
kind: Kustomization
namespace: openeuler-ccs
resources:
- console-ingress.yaml
- console-service.yaml
- console-deployment.yaml
- tls.yaml
- autoscaler.yaml
