---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    server: ccs-server
  name: ccs-server
  namespace: openeuler-ccs
spec:
  selector:
    matchLabels:
      server: ccs-server
  template:
    metadata:
      labels:
        server: ccs-server
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      nodeSelector:
        autoscaler: "true"
      containers:
      - env:
        - name: HOSTNAME
          value: openeuler-ccs-service.openeuler-ccs.svc.cluster.local
        - name: JAVA_OPTS1
          value: "
                  -Djasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}
                  -Dspring.profiles.active=prod
                  -Deureka.instance.hostname=${HOSTNAME}
                  -Deureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
                  -Deureka.client.fetch-registry=true 
                  -Deureka.client.register-with-eureka=true
                  -Deureka.client.serviceUrl.defaultZone=http://${EUREKA_CLIENT_NAME}:${EUREKA_CLIENT_PASS}@eureka-service.openeuler-ccs.svc.cluster.local:9761/eureka/
                  "
        - name: TZ
          value: Asia/Shanghai
        envFrom:
        - secretRef:
            name: openeuler-ccs-server-secrets
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/ccs-server-test:master-fe78b1
        imagePullPolicy: IfNotPresent
        name: ccs-server
        ports:
        - containerPort: 8086
          name: http
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 100
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            path: /actuator/health/readiness
            port: 8086
        livenessProbe:
          initialDelaySeconds: 100
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8086
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi