apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xihe-ingress
  namespace: xihe-test-v2
spec:
  ingressClassName: nginx
  rules:
  - host: xihe-hook-delivery.test.osinfra.cn
    http:
      paths:
      - backend:
          service:
            name: service-hook-delivery
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - xihe-hook-delivery.test.osinfra.cn
    secretName: xihe-new-tls