apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-access
  namespace: sync-bot
data:
  config.yaml: |
    access:
      repo_plugins:
        georgecaotest:
        - robot-gitee-openeuler-syncbot-test

      plugins:
      - name: robot-gitee-openeuler-syncbot-test
        endpoint: https://sync-bot.test.osinfra.cn/hook
        events:
        - "Merge Request Hook"
        - "Note Hook"