resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-website
commonAnnotations:
  kubernetes.ops.cluster: freesky-icsl-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: hk
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/icsl/opengauss-website
  newTag: 77380e397516589d5d834622c8d510bc737ee22d
