resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opengauss-website
commonAnnotations:
  kubernetes.ops.cluster: freesky-icsl-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: hk
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/icsl/opengauss-website
  newTag: f958c0f245761bc206266647b31692617784b2ff
