resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- pvc.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: chenyang244@h-partners.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: chenyang
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-doc-search
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/doc-search-test
  newName: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/openeuler/doc-search-test
  newTag: v1.0.20231026161555
