
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: sca
spec:
  replicas: 0
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      containers:
      - name: eureka
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/sca-eureka:801778e1457c511da1add445cb045a0c5d909fd8
        ports:
          - containerPort: 9000
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EUREKA_SERVER
          value: "http://eureka.sca.svc.cluster.local:9000/eureka"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: ${MY_POD_NAME}.eureka
        - name: SERVICE_NAME
          value: utralsca-eureka
        - name: APP_ENV
          value: acceptance
        - name: PACKAGE_VERSION
          value: 1.0-SNAPSHOT
        - name: MAX_HEAP_MEM
          value: 512m
        - name: INIT_HEAP_MEM
          value: 256m
        - name: CMS_IOF
          value: "75"
        - name: jasypt.encryptor.algorithm
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: jasypt_encryptor_algorithm
        - name: jasypt.encryptor.password
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: jasypt_encryptor_password
        - name: jasypt_password
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: jasypt_encryptor_password
        - name: majun.access.token
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: majun_access_token
        - name: scaSalt
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: scaSalt
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 600Mi
        volumeMounts:
        - mountPath: /work.ks
          name: secret-volume
          subPath: work_ks
        - mountPath: /primary.ks
          name: secret-volume
          subPath: primary_ks
        - mountPath: /standby.ks
          name: secret-volume
          subPath: standby_ks
        - mountPath: /opt/app/cert/
          name: data-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: sca-secret
      - name: data-volume
        persistentVolumeClaim:
          claimName: sca-volume
