apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-webserver
  namespace: om-webserver
  labels:
    app: om-webserver
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: om-webserver
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'freesky-hk-opengauss-omwebserver'
        vault.hashicorp.com/agent-inject-secret-application.properties: 'internal/data/infra-common/opengauss-omwebserver'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-application.properties: |  
          {{- with secret "internal/data/infra-common/opengauss-omwebserver" -}}  
          {{ .Data.data.application_properties }}
          {{- end }}
      labels:
        app: om-webserver
    spec:
      serviceAccountName: opengauss-omwebserver
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
        - name: om-webserver
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/om-webserver:test-pwd-7f0f5c
          env:
          - name: APPLICATION_PATH
            value: "/vault/secrets/application.properties"
          resources:
            limits:
              cpu: 2000m
              memory: 4000Mi
            requests:
              cpu: 2000m
              memory: 4000Mi
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: om-webserver
