---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cla-backend
  name: cla-backend
  namespace: cla
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: cla-backend
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'freesky-hk-cla'
        vault.hashicorp.com/agent-inject-secret-config: 'internal/data/infra-common/cla-icsl-test'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-config: |  
          {{- with secret "internal/infra-common/cla-icsl-test" -}}  
          {{ .Data.data.configIcsl }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-ca.crt: 'internal/data/infra-common/cla-icsl-test'
        vault.hashicorp.com/agent-inject-template-ca.crt: |
          {{- with secret "internal/infra-common/cla-icsl-test" -}}  
          {{ .Data.data.CA_CERT_Icsl }}
          {{- end }}
      labels:
        component: cla-backend
    spec:
      serviceAccountName: cla
      containers:
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/cla-backend:e4d3c10ce59796217020c6d8301c4532f9ea0bd8
          imagePullPolicy: IfNotPresent
          name: cla-backend-pod
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /opt/app/conf/pdfs/org_signature_pdf
              mkdir -p /opt/app/conf/pdfs/output
              /opt/app/cla-server --config-file=/vault/secrets/config
          volumeMounts:
            - mountPath: /opt/app/conf/pdfs
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: cla-data-vol