resources:
- deployment.yaml
- namespace.yaml
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn1-xihe-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: Alpine
  kubernetes.ops.owner: gouzhonglin
  kubernetes.ops.region: cn1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/oauth2-proxy
  newTag: master-965275
