---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: openlookeng-search
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-perms-application.yml: "0600"
        vault.hashicorp.com/agent-run-as-user: "1001"
        vault.hashicorp.com/role: 'freesky-hk-openlookeng-search'
        vault.hashicorp.com/agent-inject-secret-application.yml: 'internal/data/openlookeng/search-icsl'
        vault.hashicorp.com/agent-inject-template-application.yml: |  
          {{- with secret "internal/data/openlookeng/search-icsl" -}}  
          {{ .Data.data.application }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
      labels:
        app: search
    spec:
      serviceAccount: openlookeng-search
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        icsl: "true"
      containers:
      - name: search
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/openlookeng-search:8281096ff3d69918a32941c541b57ea1e507fd89
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: X_ARMOR_BACKEND_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_tenant_id
        - name: X_ARMOR_BACKEND_APP_ID
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_app_id
        - name: X_ARMOR_BACKEND_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_backend_app_token
        - name: X_ARMOR_SECURITY_ENABLE
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_security_enable
        - name: X_ARMOR_SECURITY_ROOT_PASSWORD_0
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_security_root_password
        - name: X_ARMOR_SECURITY_WORK_PASSWORD_0
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_secutiry_work_password
        - name: X_ARMOR_BACKEND_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: doc-search-secrets
              key: xarmor_backend_url
        - name: APPLICATION_PATH
          value: "/vault/secrets/application.yml"
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opt/sql
          name: sql-config-volume
      volumes:
      - name: sql-config-volume
        persistentVolumeClaim:
          claimName: openlookeng-search-ssl
