resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: zjm.514@qq.com
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: zhaojiaming
  kubernetes.ops.region: hk
namespace: cvesa-test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/cve-sa-backend/cvesa-test
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/cve-sa-backend/cvesa-test
  newTag: 6bc164a135869886038e5666ff012a2e6a63f930
