resources:
- namespace.yaml
- ingress.yaml
- pvc.yaml
- secrets.yaml
- configmap.yaml
- backend
- database
- distgit
- frontend
- keygen
- resalloc
namespace: fedora-copr
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend-test
  newTag: v1.0.20231007153515
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend_httpd-test
  newTag: v1.0.20231017100439
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/distgit-test
  newTag: v1.0.20230921210552
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/frontend-test
  newTag: v1.0.20230921211057
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/keygen-signd-test
  newTag: v1.0.20230921211428
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/resalloc-test
  newTag: v1.0.20231028164139
