---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-website-revision-tls
  namespace: openlookeng-website
spec:
  name: opengauss-website-revision-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.key:
      path: secrets/data/infra-test/domain-tls
      key: tls.key