resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- autoscaler.yaml
- secret.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: hk
namespace: mindspore-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/mindspore-website-test
  newTag: v1.0.20231028182141
