resources:
- ingress.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn1-mail-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: chenzeng
  kubernetes.ops.region: beijing
namespace: cla-migration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/icsl/cla-backend
  newTag: f2f89ed7d30e4feabafe990b2ff9612fba2c7874
